"use strict";

/*
========================================================
PROJECT FILE HUB
MIL PROJECT • GAME DEVELOPMENT
========================================================

KEY SYSTEM

Username:
    Sunnel

Generated key:
    Sunnel-mil-X7K2P9Q4

IMPORTANT:

- Key is generated SERVER-SIDE.
- Key is never generated by the browser.
- Only SHA-256 hash is stored in PostgreSQL.
- Original key is returned to browser once after upload.
- User must save the key.
- File deletion requires the key.
- Uploaded files are stored as BYTEA.
- Uploaded files are never executed by this server.
========================================================
*/

const express = require("express");
const multer = require("multer");
const crypto = require("crypto");
const path = require("path");
const { Pool } = require("pg");

const app = express();

const PORT =
    Number(process.env.PORT) || 10000;

const MAX_FILE_SIZE =
    50 * 1024 * 1024;

/*
========================================================
ALLOWED FILE TYPES
========================================================
*/

const ALLOWED_EXTENSIONS = new Set([
    "txt",
    "json",
    "gd",
    "js",
    "css",
    "html",
    "glb",
    "gltf",
    "png",
    "jpg",
    "jpeg",
    "webp",
    "wav",
    "mp3",
    "zip"
]);

/*
Only TXT files are treated as custom scripts.
*/

const SCRIPT_EXTENSIONS = new Set([
    "txt"
]);

/*
========================================================
DATABASE
========================================================
*/

if (!process.env.DATABASE_URL) {
    console.warn(
        "WARNING: DATABASE_URL is not configured."
    );
}

const pool = new Pool({
    connectionString:
        process.env.DATABASE_URL,

    ssl:
        process.env.NODE_ENV === "production"
            ? {
                rejectUnauthorized: false
            }
            : false,

    max: 10,

    idleTimeoutMillis: 30000,

    connectionTimeoutMillis: 10000
});

/*
========================================================
EXPRESS
========================================================
*/

app.disable("x-powered-by");

app.use(
    express.json({
        limit: "2mb"
    })
);

app.use(
    express.urlencoded({
        extended: true,
        limit: "2mb"
    })
);

/*
========================================================
MULTER
========================================================
*/

const upload = multer({
    storage:
        multer.memoryStorage(),

    limits: {
        fileSize:
            MAX_FILE_SIZE
    },

    fileFilter:
        (req, file, callback) => {

            const extension =
                getExtension(
                    file.originalname
                );

            if (
                !ALLOWED_EXTENSIONS.has(
                    extension
                )
            ) {
                return callback(
                    new Error(
                        "This file type is not supported."
                    )
                );
            }

            callback(null, true);
        }
});

/*
========================================================
DATABASE INITIALIZATION
========================================================
*/

async function initializeDatabase() {

    await pool.query(`
        CREATE TABLE IF NOT EXISTS files (

            id UUID PRIMARY KEY,

            name TEXT NOT NULL,

            display_name TEXT NOT NULL,

            uploader TEXT NOT NULL,

            extension TEXT NOT NULL,

            mime_type TEXT NOT NULL,

            size BIGINT NOT NULL,

            uploaded_at
                TIMESTAMPTZ NOT NULL
                DEFAULT NOW(),

            downloads
                BIGINT NOT NULL
                DEFAULT 0,

            is_script
                BOOLEAN NOT NULL
                DEFAULT FALSE,

            data BYTEA NOT NULL,

            delete_token_hash
                TEXT NOT NULL

        );
    `);

    await pool.query(`
        CREATE INDEX IF NOT EXISTS
        files_uploaded_at_idx
        ON files(uploaded_at DESC);
    `);

    await pool.query(`
        CREATE INDEX IF NOT EXISTS
        files_uploader_idx
        ON files(uploader);
    `);

    await pool.query(`
        CREATE INDEX IF NOT EXISTS
        files_extension_idx
        ON files(extension);
    `);

    console.log(
        "Database initialized."
    );
}

/*
========================================================
HELPERS
========================================================
*/

function generateId() {

    return crypto.randomUUID();
}

/*
========================================================
USERNAME CLEANING
========================================================

Example:

John Doe
    ->
John-Doe

John_123
    ->
John-123
========================================================
*/

function cleanUsernameForKey(
    username
) {

    let value =
        String(username || "")
            .trim();

    value =
        value.replace(
            /[^a-zA-Z0-9_-]+/g,
            "-"
        );

    value =
        value.replace(
            /[-_]+/g,
            "-"
        );

    value =
        value.replace(
            /^-+|-+$/g,
            ""
        );

    if (!value) {
        value = "User";
    }

    return value.slice(
        0,
        40
    );
}

/*
========================================================
RANDOM KEY CODE
========================================================

Ambiguous characters are excluded:

0
O
I
1
========================================================
*/

function generateRandomCode(
    length = 8
) {

    const alphabet =
        "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";

    let code = "";

    while (
        code.length < length
    ) {

        const byte =
            crypto.randomBytes(1)[0];

        const index =
            byte % alphabet.length;

        code +=
            alphabet[index];
    }

    return code;
}

/*
========================================================
GENERATE DELETE KEY
========================================================
*/

function generateDeleteToken(
    username
) {

    const safeUsername =
        cleanUsernameForKey(
            username
        );

    const randomCode =
        generateRandomCode(8);

    return (
        `${safeUsername}-mil-${randomCode}`
    );
}

/*
========================================================
HASH DELETE KEY
========================================================
*/

function hashToken(
    token
) {

    return crypto
        .createHash("sha256")
        .update(token, "utf8")
        .digest("hex");
}

/*
========================================================
CLEAN TEXT
========================================================
*/

function cleanText(
    value,
    maxLength
) {

    if (
        typeof value !==
        "string"
    ) {
        return "";
    }

    return value
        .trim()
        .replace(/\s+/g, " ")
        .slice(
            0,
            maxLength
        );
}

/*
========================================================
EXTENSION
========================================================
*/

function getExtension(
    filename
) {

    return path
        .extname(
            filename || ""
        )
        .slice(1)
        .toLowerCase();
}

/*
========================================================
SAFE FILE RESPONSE
========================================================
*/

function safePublicFile(
    row
) {

    return {

        id:
            row.id,

        name:
            row.name,

        displayName:
            row.display_name,

        uploader:
            row.uploader,

        extension:
            row.extension,

        type:
            row.mime_type,

        size:
            Number(row.size),

        date:
            new Date(
                row.uploaded_at
            ).getTime(),

        downloads:
            Number(row.downloads),

        script:
            Boolean(row.is_script)

    };
}

/*
========================================================
REAL-TIME CLIENTS
========================================================
*/

const clients =
    new Set();

function broadcastLibraryUpdate() {

    const payload = {
        timestamp:
            Date.now()
    };

    const message =
        "event: library-update\n" +
        "data: " +
        JSON.stringify(payload) +
        "\n\n";

    for (
        const client of clients
    ) {

        try {

            client.write(
                message
            );

        }

        catch {

            clients.delete(
                client
            );
        }
    }
}

/*
========================================================
SERVER-SENT EVENTS
========================================================
*/

app.get(
    "/api/events",
    (req, res) => {

        res.setHeader(
            "Content-Type",
            "text/event-stream"
        );

        res.setHeader(
            "Cache-Control",
            "no-cache, no-transform"
        );

        res.setHeader(
            "Connection",
            "keep-alive"
        );

        res.setHeader(
            "X-Accel-Buffering",
            "no"
        );

        res.flushHeaders();

        res.write(
            "event: connected\n" +
            "data: " +
            JSON.stringify({
                connected: true
            }) +
            "\n\n"
        );

        clients.add(res);

        const heartbeat =
            setInterval(
                () => {

                    try {

                        res.write(
                            ": heartbeat\n\n"
                        );

                    }
                    catch {

                        clearInterval(
                            heartbeat
                        );

                        clients.delete(
                            res
                        );
                    }

                },
                25000
            );

        req.on(
            "close",
            () => {

                clearInterval(
                    heartbeat
                );

                clients.delete(
                    res
                );
            }
        );
    }
);

/*
========================================================
GET FILES
========================================================
*/

app.get(
    "/api/files",
    async (req, res) => {

        try {

            const search =
                cleanText(
                    req.query.search || "",
                    100
                );

            const uploader =
                cleanText(
                    req.query.uploader || "",
                    100
                );

            const sort =
                String(
                    req.query.sort ||
                    "newest"
                );

            const values = [];

            const conditions = [];

            if (search) {

                values.push(
                    `%${search}%`
                );

                const parameter =
                    `$${values.length}`;

                conditions.push(`
                    (
                        name ILIKE ${parameter}
                        OR display_name ILIKE ${parameter}
                        OR uploader ILIKE ${parameter}
                        OR extension ILIKE ${parameter}
                    )
                `);
            }

            if (uploader) {

                values.push(
                    uploader
                );

                conditions.push(
                    `uploader = $${values.length}`
                );
            }

            let orderBy =
                "uploaded_at DESC";

            if (
                sort === "oldest"
            ) {

                orderBy =
                    "uploaded_at ASC";

            } else if (
                sort === "name"
            ) {

                orderBy =
                    "LOWER(display_name) ASC";

            } else if (
                sort === "largest"
            ) {

                orderBy =
                    "size DESC";

            } else if (
                sort === "downloads"
            ) {

                orderBy =
                    "downloads DESC";
            }

            const query = `
                SELECT

                    id,
                    name,
                    display_name,
                    uploader,
                    extension,
                    mime_type,
                    size,
                    uploaded_at,
                    downloads,
                    is_script

                FROM files

                ${
                    conditions.length
                        ? `WHERE ${conditions.join(
                            " AND "
                        )}`
                        : ""
                }

                ORDER BY ${orderBy}

                LIMIT 500
            `;

            const result =
                await pool.query(
                    query,
                    values
                );

            res.json({

                success:
                    true,

                files:
                    result.rows.map(
                        safePublicFile
                    )

            });

        }
        catch (error) {

            console.error(
                "GET /api/files:",
                error
            );

            res.status(500).json({

                success:
                    false,

                error:
                    "Unable to load files."

            });
        }
    }
);

/*
========================================================
GET UPLOADERS
========================================================
*/

app.get(
    "/api/uploaders",
    async (req, res) => {

        try {

            const result =
                await pool.query(`
                    SELECT DISTINCT
                        uploader

                    FROM files

                    ORDER BY
                        LOWER(uploader) ASC
                `);

            res.json({

                success:
                    true,

                uploaders:
                    result.rows.map(
                        row =>
                            row.uploader
                    )

            });

        }
        catch (error) {

            console.error(
                "GET /api/uploaders:",
                error
            );

            res.status(500).json({

                success:
                    false,

                error:
                    "Unable to load uploaders."

            });
        }
    }
);

/*
========================================================
STATISTICS
========================================================
*/

app.get(
    "/api/stats",
    async (req, res) => {

        try {

            const result =
                await pool.query(`
                    SELECT

                        COUNT(*)::BIGINT
                            AS files,

                        COUNT(*)
                            FILTER (
                                WHERE is_script = TRUE
                            )::BIGINT
                            AS scripts,

                        COALESCE(
                            SUM(size),
                            0
                        )::BIGINT
                            AS total_size,

                        COALESCE(
                            SUM(downloads),
                            0
                        )::BIGINT
                            AS downloads

                    FROM files
                `);

            const row =
                result.rows[0];

            res.json({

                success:
                    true,

                stats: {

                    files:
                        Number(
                            row.files
                        ),

                    scripts:
                        Number(
                            row.scripts
                        ),

                    totalSize:
                        Number(
                            row.total_size
                        ),

                    downloads:
                        Number(
                            row.downloads
                        )
                }
            });

        }
        catch (error) {

            console.error(
                "GET /api/stats:",
                error
            );

            res.status(500).json({

                success:
                    false,

                error:
                    "Unable to load statistics."

            });
        }
    }
);

/*
========================================================
UPLOAD
========================================================

THIS IS THE MAIN KEY SYSTEM.
========================================================
*/

app.post(
    "/api/files",
    upload.single("file"),
    async (req, res) => {

        try {

            /*
            --------------------------------------------
            FILE REQUIRED
            --------------------------------------------
            */

            if (!req.file) {

                return res.status(
                    400
                ).json({

                    success:
                        false,

                    error:
                        "Please select a file."

                });
            }

            /*
            --------------------------------------------
            USERNAME REQUIRED
            --------------------------------------------
            */

            const uploader =
                cleanText(
                    req.body.uploader,
                    80
                );

            if (!uploader) {

                return res.status(
                    400
                ).json({

                    success:
                        false,

                    error:
                        "Username is required before publishing."

                });
            }

            /*
            --------------------------------------------
            DISPLAY NAME
            --------------------------------------------
            */

            const displayName =
                cleanText(
                    req.body.displayName,
                    100
                ) ||
                path.basename(
                    req.file.originalname,
                    path.extname(
                        req.file.originalname
                    )
                );

            /*
            --------------------------------------------
            EXTENSION
            --------------------------------------------
            */

            const extension =
                getExtension(
                    req.file.originalname
                );

            if (
                !ALLOWED_EXTENSIONS.has(
                    extension
                )
            ) {

                return res.status(
                    400
                ).json({

                    success:
                        false,

                    error:
                        "This file type is not allowed."

                });
            }

            /*
            --------------------------------------------
            SIZE
            --------------------------------------------
            */

            if (
                req.file.size >
                MAX_FILE_SIZE
            ) {

                return res.status(
                    413
                ).json({

                    success:
                        false,

                    error:
                        "File exceeds the 50 MB limit."

                });
            }

            /*
            --------------------------------------------
            SCRIPT
            --------------------------------------------
            */

            const isScript =
                SCRIPT_EXTENSIONS.has(
                    extension
                );

            /*
            --------------------------------------------
            GENERATE DELETE KEY
            --------------------------------------------

            EXAMPLE:

            Sunnel-mil-X7K2P9Q4
            */

            const deleteToken =
                generateDeleteToken(
                    uploader
                );

            /*
            --------------------------------------------
            HASH KEY
            --------------------------------------------

            PostgreSQL receives ONLY this hash.
            */

            const deleteTokenHash =
                hashToken(
                    deleteToken
                );

            /*
            --------------------------------------------
            GENERATE FILE ID
            --------------------------------------------
            */

            const id =
                generateId();

            /*
            --------------------------------------------
            SAVE FILE
            --------------------------------------------
            */

            await pool.query(
                `
                INSERT INTO files (

                    id,
                    name,
                    display_name,
                    uploader,
                    extension,
                    mime_type,
                    size,
                    is_script,
                    data,
                    delete_token_hash

                )

                VALUES (

                    $1,
                    $2,
                    $3,
                    $4,
                    $5,
                    $6,
                    $7,
                    $8,
                    $9,
                    $10

                )
                `,
                [

                    id,

                    req.file.originalname,

                    displayName,

                    uploader,

                    extension,

                    req.file.mimetype ||
                        "application/octet-stream",

                    req.file.size,

                    isScript,

                    req.file.buffer,

                    deleteTokenHash

                ]
            );

            /*
            --------------------------------------------
            NOTIFY CLIENTS
            --------------------------------------------
            */

            broadcastLibraryUpdate();

            /*
            --------------------------------------------
            RETURN KEY ONCE
            --------------------------------------------

            IMPORTANT:

            deleteToken is NOT written to PostgreSQL.

            The browser receives it here so the popup
            can display it.
            */

            return res.status(
                201
            ).json({

                success:
                    true,

                file: {

                    id,

                    name:
                        req.file.originalname,

                    displayName,

                    uploader,

                    extension,

                    type:
                        req.file.mimetype ||
                        "application/octet-stream",

                    size:
                        req.file.size,

                    script:
                        isScript

                },

                deleteToken,

                deleteKey: {

                    format:
                        "username-mil-RANDOMCODE",

                    warning:
                        "Save this key. It cannot be recovered if you lose it."

                }

            });

        }
        catch (error) {

            console.error(
                "POST /api/files:",
                error
            );

            if (
                error.code ===
                "LIMIT_FILE_SIZE"
            ) {

                return res.status(
                    413
                ).json({

                    success:
                        false,

                    error:
                        "File exceeds the 50 MB limit."

                });
            }

            return res.status(
                500
            ).json({

                success:
                    false,

                error:
                    "Upload failed."

            });
        }
    }
);

/*
========================================================
FILE DETAILS
========================================================
*/

app.get(
    "/api/files/:id",
    async (req, res) => {

        try {

            const result =
                await pool.query(
                    `
                    SELECT

                        id,
                        name,
                        display_name,
                        uploader,
                        extension,
                        mime_type,
                        size,
                        uploaded_at,
                        downloads,
                        is_script

                    FROM files

                    WHERE id = $1
                    `,
                    [
                        req.params.id
                    ]
                );

            if (
                !result.rows.length
            ) {

                return res.status(
                    404
                ).json({

                    success:
                        false,

                    error:
                        "File not found."

                });
            }

            res.json({

                success:
                    true,

                file:
                    safePublicFile(
                        result.rows[0]
                    )

            });

        }
        catch (error) {

            console.error(
                error
            );

            res.status(500).json({

                success:
                    false,

                error:
                    "Unable to load file."

            });
        }
    }
);

/*
========================================================
DOWNLOAD
========================================================
*/

app.get(
    "/api/files/:id/download",
    async (req, res) => {

        try {

            const result =
                await pool.query(
                    `
                    SELECT

                        name,
                        mime_type,
                        data

                    FROM files

                    WHERE id = $1
                    `,
                    [
                        req.params.id
                    ]
                );

            if (
                !result.rows.length
            ) {

                return res.status(
                    404
                ).send(
                    "File not found."
                );
            }

            const file =
                result.rows[0];

            await pool.query(
                `
                UPDATE files

                SET downloads =
                    downloads + 1

                WHERE id = $1
                `,
                [
                    req.params.id
                ]
            );

            res.setHeader(
                "Content-Type",
                file.mime_type ||
                    "application/octet-stream"
            );

            res.setHeader(
                "Content-Disposition",
                `attachment; filename*=UTF-8''${encodeURIComponent(
                    file.name
                )}`
            );

            res.setHeader(
                "Content-Length",
                file.data.length
            );

            res.send(
                file.data
            );

            broadcastLibraryUpdate();

        }
        catch (error) {

            console.error(
                "DOWNLOAD:",
                error
            );

            res.status(500).send(
                "Download failed."
            );
        }
    }
);

/*
========================================================
SCRIPT PREVIEW
========================================================
*/

app.get(
    "/api/files/:id/preview",
    async (req, res) => {

        try {

            const result =
                await pool.query(
                    `
                    SELECT

                        id,
                        name,
                        display_name,
                        uploader,
                        extension,
                        mime_type,
                        size,
                        uploaded_at,
                        downloads,
                        is_script,
                        data

                    FROM files

                    WHERE id = $1
                    `,
                    [
                        req.params.id
                    ]
                );

            if (
                !result.rows.length
            ) {

                return res.status(
                    404
                ).json({

                    success:
                        false,

                    error:
                        "File not found."

                });
            }

            const file =
                result.rows[0];

            if (
                !file.is_script
            ) {

                return res.status(
                    400
                ).json({

                    success:
                        false,

                    error:
                        "This file is not a script."

                });
            }

            res.json({

                success:
                    true,

                file: {

                    id:
                        file.id,

                    name:
                        file.name,

                    displayName:
                        file.display_name,

                    uploader:
                        file.uploader,

                    extension:
                        file.extension,

                    type:
                        file.mime_type,

                    size:
                        Number(
                            file.size
                        ),

                    date:
                        new Date(
                            file.uploaded_at
                        ).getTime(),

                    downloads:
                        Number(
                            file.downloads
                        ),

                    script:
                        true,

                    content:
                        file.data.toString(
                            "utf8"
                        )
                }
            });

        }
        catch (error) {

            console.error(
                "PREVIEW:",
                error
            );

            res.status(500).json({

                success:
                    false,

                error:
                    "Unable to preview script."

            });
        }
    }
);

/*
========================================================
DELETE FILE
========================================================

Client sends:

{
    "deleteToken":
        "Sunnel-mil-X7K2P9Q4"
}

Server hashes it and compares it to PostgreSQL.
========================================================
*/

app.delete(
    "/api/files/:id",
    async (req, res) => {

        try {

            const deleteToken =
                typeof req.body?.deleteToken ===
                "string"
                    ? req.body.deleteToken.trim()
                    : "";

            if (!deleteToken) {

                return res.status(
                    400
                ).json({

                    success:
                        false,

                    error:
                        "Delete key is required."

                });
            }

            const deleteTokenHash =
                hashToken(
                    deleteToken
                );

            const result =
                await pool.query(
                    `
                    DELETE FROM files

                    WHERE id = $1

                    AND delete_token_hash = $2

                    RETURNING id
                    `,
                    [
                        req.params.id,
                        deleteTokenHash
                    ]
                );

            if (
                !result.rows.length
            ) {

                return res.status(
                    403
                ).json({

                    success:
                        false,

                    error:
                        "Invalid delete key."

                });
            }

            broadcastLibraryUpdate();

            res.json({

                success:
                    true,

                message:
                    "File deleted successfully."

            });

        }
        catch (error) {

            console.error(
                "DELETE:",
                error
            );

            res.status(500).json({

                success:
                    false,

                error:
                    "Delete failed."

            });
        }
    }
);

/*
========================================================
HEALTH
========================================================
*/

app.get(
    "/api/health",
    async (req, res) => {

        try {

            await pool.query(
                "SELECT 1"
            );

            res.json({

                success:
                    true,

                status:
                    "online",

                database:
                    "connected"

            });

        }
        catch {

            res.status(
                503
            ).json({

                success:
                    false,

                status:
                    "offline",

                database:
                    "disconnected"

            });
        }
    }
);

/*
========================================================
FRONTEND
========================================================
*/

const publicDirectory =
    path.join(
        __dirname,
        "public"
    );

app.use(
    express.static(
        publicDirectory
    )
);

/*
========================================================
SPA FALLBACK
========================================================
*/

app.get(
    "/{*splat}",
    (req, res) => {

        res.sendFile(
            path.join(
                publicDirectory,
                "index.html"
            ),
            error => {

                if (
                    error &&
                    !res.headersSent
                ) {

                    res.status(
                        404
                    ).send(
                        "Frontend not found."
                    );
                }
            }
        );
    }
);

/*
========================================================
ERROR HANDLER
========================================================
*/

app.use(
    (error, req, res, next) => {

        console.error(
            "SERVER ERROR:",
            error
        );

        if (
            error instanceof
            multer.MulterError
        ) {

            if (
                error.code ===
                "LIMIT_FILE_SIZE"
            ) {

                return res.status(
                    413
                ).json({

                    success:
                        false,

                    error:
                        "Maximum file size is 50 MB."

                });
            }

            return res.status(
                400
            ).json({

                success:
                    false,

                error:
                    error.message

            });
        }

        if (
            error?.message ===
            "This file type is not supported."
        ) {

            return res.status(
                400
            ).json({

                success:
                    false,

                error:
                    "This file type is not supported."

            });
        }

        if (
            res.headersSent
        ) {

            return next(
                error
            );
        }

        res.status(500).json({

            success:
                false,

            error:
                "Unexpected server error."

        });
    }
);

/*
========================================================
START
========================================================
*/

async function startServer() {

    try {

        await initializeDatabase();

        app.listen(
            PORT,
            "0.0.0.0",
            () => {

                console.log(
                    "================================"
                );

                console.log(
                    "PROJECT FILE HUB"
                );

                console.log(
                    "Server running on port " +
                    PORT
                );

                console.log(
                    "Maximum upload: 50 MB"
                );

                console.log(
                    "Delete keys: ENABLED"
                );

                console.log(
                    "PostgreSQL: CONNECTED"
                );

                console.log(
                    "================================"
                );
            }
        );

    }
    catch (error) {

        console.error(
            "SERVER START FAILED"
        );

        console.error(
            error
        );

        process.exit(1);
    }
}

startServer();

/*
========================================================
SHUTDOWN
========================================================
*/

async function shutdown(
    signal
) {

    console.log(
        `${signal} received.`
    );

    for (
        const client of clients
    ) {

        try {
            client.end();
        }
        catch {}
    }

    try {

        await pool.end();

    }
    catch (error) {

        console.error(
            error
        );
    }

    process.exit(0);
}

process.on(
    "SIGTERM",
    () =>
        shutdown("SIGTERM")
);

process.on(
    "SIGINT",
    () =>
        shutdown("SIGINT")
);
